version: "3.8"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    restart: unless-stopped
    ports: [ "2181:2181" ]

  kafka:
    image: wurstmeister/kafka
    restart: unless-stopped
    ports: [ "9092:9092" ]
    hostname: kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CREATE_TOPICS: "test_topic:1:1"
    depends_on: [ "zookeeper" ]

  database:
    image: mongo
    container_name: mongodb
    ports: [ "27017:27017" ]
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "1234"

  createbook:
    build: createbook
    container_name: createbook
    restart: unless-stopped
    ports: [ "8080:8080" ]
    environment:
      PORT: "8080"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      DATABASE_USER: "root"
      DATABASE_PASSWORD: "1234"

  listbooks:
    build: listbooks
    container_name: listbooks
    restart: unless-stopped
    ports: [ "9090:9090" ]
    environment:
      PORT: "9090"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      DATABASE_USER: "root"
      DATABASE_PASSWORD: "1234"
